#!/bin/sh
# ----------------------------------------------------------------------------
# Zookeeper client command line tool
# ----------------------------------------------------------------------------

if [ -z "$JAVA_HOME" ] ; then
  echo .
  echo Error: JAVA_HOME not found in your environment. >&2
  echo Please set the JAVA_HOME variable in your environment to match the >&2
  echo location of your Java installation. >&2
  echo .
  exit 1
fi

if [ ! -x "$JAVA_HOME/bin/java" ]; then
  echo .
  echo Error: JAVA_HOME is set to an invalid directory. >&2
  echo JAVA_HOME = "$JAVA_HOME" >&2
  echo Please set the JAVA_HOME variable in your environment to match the >&2
  echo location of your Java installation. >&2
  echo .
  exit 1
fi

ZK_CMD_LINE_ARGS=$*

cd `dirname $0`
cd ..
ZK_HOME=`pwd`

ZK_JAVA_EXE="$JAVA_HOME/bin/java"

ZK_AGENT_JAR=$ZK_HOME/agent/zookeeper-cli-agent.jar

ZK_APPLICATION_JAR=$ZK_HOME/boot/zookeeper-cli-application.jar

$ZK_JAVA_EXE -javaagent:$ZK_AGENT_JAR -jar $ZK_APPLICATION_JAR $ZK_CMD_LINE_ARGS
if [ $? -eq 1 ]; then
    exit 1
fi

exit 0